version: 0.1

phases:
  install:
    commands:
      - echo [`date`] phases install started
  pre_build:
    commands:
      - echo [`date`] phases pre_build started
      - rspec
  build:
    commands:
      - echo [`date`] phases build started
      - echo ==================
      - echo $CODEBUILD_SOURCE_VERSION
      - echo $CODEBUILD_WEBHOOK_EVENT
      - echo $CODEBUILD_WEBHOOK_PULL_REQUEST_MERGED
      - echo $CODEBUILD_WEBHOOK_TRIGGER
      - echo ${CODEBUILD_WEBHOOK_TRIGGER#branch/}
    # - yes Y | jets deploy development
  post_build:
    commands:
      - echo [`date`] phases post_build started
