version: 0.1

phases:
  install:
    commands:
      - echo [`date`] phases install started
  pre_build:
    commands:
      - echo [`date`] phases pre_build started
  build:
    commands:
      - echo [`date`]phases build started
      - rspec
  post_build:
    commands:
      - echo [`date`]phases post_build started
